### PR TITLE
Fix the error transformer for the v2 error

### LINKED ISSUE #177: GoogleAdsError never raise in v2
After the v2 update, the exception `Google::Ads::GoogleAds::Errors::GoogleAdsError` never raise.

### PR DESCRIPTION
**Pull request by samphippen**
Fixes #177

### CODE REVIEW

File: lib/google/ads/google_ads/service_lookup.rb [hunk 1]
```diff
@@ -80,17 +80,22 @@ def validate_login_customer_id
           begin
             gax_error.status_details.each do |detail|
               # If there is an underlying GoogleAdsFailure, throw that one.
-              if detail.is_a?(
-                  Google::Ads::GoogleAds::V1::Errors::GoogleAdsFailure)
+              if [
+                Google::Ads::GoogleAds::V1::Errors::GoogleAdsFailure === detail,
```
Comment (mcloonan) [inline lib/google/ads/google_ads/service_lookup.rb]: We have a list of known versions. Can we soft-code this so we don't have to update it every time a new version is added or removed?

Also, even if we wanted to keep it this way, is there some advantage to using this wonky syntax over a normal `||` comparison?
